### ISSUE TITLE
Replace TF Consent form [13,3,4.33]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/curiosity-machine#2460]
New form: https://docs.google.com/document/d/17evRJSzZtH_TyzWPbfwOaCJG_-G7hXytVIAV1gvYijc/edit?ts=5ff540d2

- For families
- On hellosign for students

**Comment by shaun-technovation** [comment]
Thanks for adding the HelloSign steps @rsgonzal!  🎉 🍰 🙌 😀

**Comment by ksrebecca** [comment]
QAed this one. 

Updated form showed up for family account creation and was mailed to parent for student account creation. Both new accounts able to log in and access site and on back end both users show as fully active, so looks good to me! Thank you!!!

PS I think we can leave the privacy email as is for now until we need to update the consent form again.

PPS I sent Rox an email that is super outdated. Could be a fun project for Agility?
